### ISSUE TITLE
create-dev-env.sh is failing at azdev setup --repo . --ext capi --verbose

### ISSUE THREAD

**Issue by marosset** [Azure/azure-capi-cli-extension#181]
I tried to run `./create-dev-env.sh` both in the dev container (through VS code) and in locally in a WSL2 environement and both times I got the following errors

```bash
 + azdev setup --repo . --ext capi --verbose
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (5.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/marosset/.local/bin/azdev", line 8, in <module>
    sys.exit(main())
  File "/home/marosset/.local/lib/python3.8/site-packages/azdev/__main__.py", line 39, in main
    config_dir=get_azdev_config_dir())
  File "/home/marosset/.local/lib/python3.8/site-packages/azdev/utilities/config.py", line 24, in get_azdev_config_dir
    _, env_name = os.path.splitdrive(get_env_path())
  File "/usr/lib/python3.8/posixpath.py", line 134, in splitdrive
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Here is the version of the azure cli i'm using if that matters

```bash
az version
Azure-cli    Azure-cli-core    Azure-cli-telemetry
-----------  ----------------  ---------------------
2.45.0       2.45.0            1.0.8
```

**Comment by mboersma** [comment]
FWIW, I opened the project with CodeSpaces and my local VS Code and it's fine. But this is macOS and python 3.10.

**Comment by marosset** [comment]
I opened the project with CodeSpaces and it worked fine too.

I noticed that when i run `create-dev-env.sh` from inside a WSL environment, it looks like the python virtualenv isn't getting configured properly. What is strand is that if i run all of the commands from that script manually I can get the dev env working 🤷‍♂️
